name: EasyReport
version: '1.0'
main: com.ender.easyReport.EasyReport
api-version: '1.19'
authors: [ EnderRogue81 ]
description: A simple and effective way to deal with reports.

commands:
  report:
    description: Report a player for violating server rules.
    usage: /report <player>
    permission: quickreport.report
    permission-message: You do not have permission to use this command.
  reports:
    description: View all active reports.
    usage: /reports
    permission: quickreport.staff
    permission-message: You do not have permission to view reports.
  easyreport:
    description: Manages the EasyReport plugin.
    usage: /easyreport reload
    aliases: [er]
    permission: quickreport.reload
    permission-message: You do not have permission to use this command.

permissions:
  quickreport.report:
    description: Allows players to use the /report command.
    default: true
  quickreport.staff:
    description: Allows staff to use the /reports command and view notifications.
    default: op
  quickreport.reload:
    description: Allows staff to reload the EasyReport configuration.
    default: op